name: CI TEST ${{ inputs.branch_name }}
run-name: AAAA ${{ inputs.branch_name }}
on: 
  workflow_dispatch:
    inputs:
      branch_name:
        default: "AA"

permissions: 
   pull-requests: write 
   
jobs:
  cit_est:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          echo Run Build and Test
          exit 1

      - name: Success Comment
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ github.head_ref }} 브랜치 빌드 테스트에 성공했습니다! :tada:
            
      - name: Failure Comment
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ github.head_ref }} 브랜치 빌드 테스트에 실패했습니다! :x:
            아래 로그를 확인해주세요!
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
